logging:
  level:
    org.springframework: INFO
    org.springframework.jdbc: INFO
#    org.springframework.security: DEBUG
#    org.thymeleaf: DEBUG
    com.example: DEBUG
    

# 拡張フレームワーク機能の設定
example:
# 帳票出力機能の設定
#  report:
# コンパイル済の様式ファイルを保管する一時ディレクトリを変更する場合に設定
#    jasper-file-tmpdir: jasper2

# 一時ファイル作成機能の設定
#  file:
# 一時保存するディレクトリ  
#    base-dir: tmpFilesDir2
# 一時ファイルを削除するスケジュール
#    delete-initial-delay-seconds: 120
#    delete-fixed-rate-seconds: 60
# 一時ファイルの保存期間（秒）
#    expiration-seconds: 60

# 鍵管理機能の設定
  keymanagement:
    # オブジェクトストレージで管理されているKMSの署名鍵の証明書
    # 開発時は自己署名証明書のpemファイルを使用するように設定している
    cert-pem-file-name: self-certificate.pem
    # 公開鍵情報作成時にjava.securityのKeyFactoryで指定するアルゴリズム(RSASSA-PSSに設定変更する場合に指定）
    #key-factory-algorithm: RSASSA-PSS
    # CSR/自己署名証明書作成時の署名アルゴリズム(RSASSA-PSSに設定変更する場合に指定）
    #signature-algorithm: SHA256WITHRSAANDMGF1
    aws-kms:
      # 鍵が管理されているAWS KMSのリージョンを設定
      region: ap-northeast-1
      #region: ap-northeast-3
      # KMSにキー作成する場合のキー仕様(RSASSA-PSSに設定変更する場合に指定）
      #key-spec: RSA_2048
      # KMSの署名アルゴリズム名(RSASSA-PSSに設定変更する場合に指定）
      #kms-signing-algorithm-spec: RSASSA_PSS_SHA_256

# 電子署名機能の設定
  digitalsignature:
# PKCS#12のキーストアを使用して基本署名を行う場合に設定
#    type: pkcs12-basic
# PAdES署名の場合の設定
# PKCS#12のキーストアを使用してPADES署名(PADES-B-B)を行う場合に設定
    type: pkcs12-pades
    pkcs12:
      # PKCS#12のキーストアファイル名(SHA256 WITH RSA)
#      keystore-file-path: certs/pkcs12/rsa/keystore.p12
      # PKCS#12のキーストアファイル名(SHA256 WITH ECDSA)
      keystore-file-path: certs/pkcs12/ecdsa/keystore.p12
      # PKCS#12のキーストアパスワード
      password: password123
# AWS KMSを使用してPADES署名(PADES-B-B)を行う場合に設定
#    type: aws-kms-pades
    aws-kms:
      # キーIDとキーエイリアスのどちらか一方を設定
      # 署名に使用するAWS KMSのキーIDを設定
      #key-id: 713cdf19-8ad3-4659-be76-6547c0a65f7c
      # 署名に使用するAWS KMSのキーエイリアス（alias/は除く）を設定
      key-alias: digital-signature-key


# オブジェクトストレージの設定
  s3:
    localfake:
#S3 Fake by local file system
      type: file
      base-dir: C:\tmp\objectstorage
#S3 Fake by LocalStack
#      type: localstack
#      port: 4566
#      access-key-id: dummy
#      secret-access-key: dummy
#    bucket: mysd33bucket123 
#S3 Fake by s3rver    
#      type: s3rver
#      port: 4568
#    bucket: mysd33bucket123
#S3 Fake by MinIO
#      type: minio
#      port: 9000
#      access-key-id: minioadmin
#      secret-access-key: minioadmin
#    bucket: mysd33bucket123